### ISSUE TITLE
How to differentiate between in/field, hole and fringe cells

### ISSUE THREAD

**Issue by mennodeij** [jsitaraman/tioga#43]
I'm testing tioga with a 3D overset grid assembly in which one grid ('foreground') is completely within another grid ('background'). I have a couple of questions about this. 

1. When I run tioga, I only get cell status 1 or -1 on both grids, is that supposed to happen? I see that cell status of 1 is always an in/field cell, and cell status of -1 is a fringe cell on the foreground grid and a hole cell on the background grid.
2. If so, how can I differentiate between in/field cells, hole cells and fringe cells (without prior knowledge of which grid is foreground and which is background)?

**Comment by sayerhs** [comment]
@mennodeij TIOGA iblank has three states 

- Field -  where the PDEs are solved and indicated by `IBLANK = 1`
- Fringe - where data from the donor is interpolated onto this node,  indicated by `IBLANK = -1`, and 
- Hole - a node that lies inside a solid body, indicated by `IBLANK = 0`

See the following image. 

<img width="1126" alt="Screen Shot 2020-10-19 at 9 50 25 AM" src="https://user-images.githubusercontent.com/433480/96474885-866c4d80-11f0-11eb-8a9b-2c7fabd810b9.png">

Your second question doesn't make sense to me. You'll have to tell TIOGA some information about the meshes that you're sending it... specifically you'll have to give it information on the wall boundaries (so that it can identify hole nodes) and overset boundaries (so that it can tag those nodes in the *foreground* mesh that you mentioned) as mandatory fringes. If you just give it two meshes, with similar cell resolutions then it doesn't really have a good criteria to pick one vs. the other and the results might not be what you expect.

**Comment by mennodeij** [comment]
Indeed, I’m giving node tags to the boundary of the overset mesh (obcnode) and to the wall (wbcnode) using arrays in the two tioga_registergrid_data_mb calls, one for the foreground and one for the background grid. 

Thanks for pointing out the hole cutting behaviour for the background grid, that is probably why I don’t see any iblank=0 values.

**Comment by mennodeij** [comment]
Ok, it is clear to me now how this works and that `reduce_fringes` is used to cut holes.
